FROM node:20-alpine AS build

WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY apps/web/package.json apps/web/package.json

RUN corepack enable && yarn install

COPY apps/web ./apps/web

WORKDIR /app/apps/web

RUN yarn build

FROM nginx:1.27-alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/web/dist /usr/share/nginx/html

EXPOSE 80
