FROM node:20-alpine AS build

WORKDIR /app/apps/web

COPY apps/web/package.json ./

RUN corepack enable && yarn config set nodeLinker node-modules && yarn install

COPY apps/web ./

RUN yarn build

FROM nginx:1.27-alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/web/dist /usr/share/nginx/html

EXPOSE 80
